# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-04 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project',
            new_name='projects',
        ),
    ]
