# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-06 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20161204_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='images',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='projects',
            name='subtitle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='video',
            field=models.CharField(max_length=200),
        ),
    ]
