# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-07 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20161206_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='filepath',
        ),
    ]
